name: Main CI

on:
  push:
    branches: [ dev-ng ]
    paths:
      - '.github/workflows/main_ci.yml'
      - 'cmake/**'
      - 'include/**'
      - 'src/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'vcpkg.json'
  pull_request:
    branches: [ dev-ng ]
  workflow_dispatch:

env:
  VCPKG_COMMIT_ID: d72783cb3aeddfd667861caef1060e54ca6fa7a9

jobs:
  all-runtimes:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1.10.0

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v10.0
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}

      - name: Build
        uses: lukka/run-cmake@v10.0
        with:
          cmakeListsTxtPath: ${{ github.workspace }}/main/CMakeLists.txt
          configurePreset: vs2022-windows-vcpkg
          buildPreset: Debug-All
  flatrim-only:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1.10.0

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v10.0
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}

      - name: Build
        uses: lukka/run-cmake@v10.0
        with:
          cmakeListsTxtPath: ${{ github.workspace }}/main/CMakeLists.txt
          configurePreset: vs2022-windows-vcpkg-flatrim
          buildPreset: Debug-Flatrim
  pre-ae-runtimes:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1.10.0

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v10.0
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}

      - name: Build
        uses: lukka/run-cmake@v10.0
        with:
          cmakeListsTxtPath: ${{ github.workspace }}/main/CMakeLists.txt
          configurePreset: vs2022-windows-vcpkg-pre-ae
          buildPreset: Debug-Pre-AE
  se-only:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1.10.0

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v10.0
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}

      - name: Build
        uses: lukka/run-cmake@v10.0
        with:
          cmakeListsTxtPath: ${{ github.workspace }}/main/CMakeLists.txt
          configurePreset: vs2022-windows-vcpkg-se
          buildPreset: Debug-SE
  ae-only:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1.10.0

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v10.0
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}

      - name: Build
        uses: lukka/run-cmake@v10.0
        with:
          cmakeListsTxtPath: ${{ github.workspace }}/main/CMakeLists.txt
          configurePreset: vs2022-windows-vcpkg-ae
          buildPreset: Debug-AE
  vr-only:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1.10.0

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v10.0
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}

      - name: Build
        uses: lukka/run-cmake@v10.0
        with:
          cmakeListsTxtPath: ${{ github.workspace }}/main/CMakeLists.txt
          configurePreset: vs2022-windows-vcpkg-vr
          buildPreset: Debug-VR
