name: Main CI

on:
  push:
    branches: [ dev-ng ]
    paths:
      - '.github/workflows/main_ci.yml'
      - 'cmake/**'
      - 'include/**'
      - 'src/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'vcpkg.json'
  pull_request:
    branches: [ dev-ng, feature/* ]
  workflow_dispatch:

env:
  VCPKG_COMMIT_ID: d72783cb3aeddfd667861caef1060e54ca6fa7a9

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        preset:
          - Debug-All-MSVC
          - Debug-All-ClangCL
          - Debug-Flatrim-MSVC
          - Debug-Flatrim-ClangCL
          - Debug-Current-MSVC
          - Debug-Current-ClangCL
          - Debug-PreAE-MSVC
          - Debug-PreAE-ClangCL
          - Debug-AE-MSVC
          - Debug-AE-ClangCL
          - Debug-SE-MSVC
          - Debug-SE-ClangCL
          - Debug-VR-MSVC
          - Debug-VR-ClangCL
          - Release-All-MSVC
          - Release-All-ClangCL
          - Release-Flatrim-MSVC
          - Release-Flatrim-ClangCL
          - Release-Current-MSVC
          - Release-Current-ClangCL
          - Release-PreAE-MSVC
          - Release-PreAE-ClangCL
          - Release-AE-MSVC
          - Release-AE-ClangCL
          - Release-SE-MSVC
          - Release-SE-ClangCL
          - Release-VR-MSVC
          - Release-VR-ClangCL
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1.10.0

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v10.0
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}

      - name: Build
        uses: lukka/run-cmake@v10.0
        with:
          cmakeListsTxtPath: ${{ github.workspace }}/main/CMakeLists.txt
          configurePreset: ${{ matrix.preset }}
          buildPreset: ${{ matrix.preset }}
